---
title: "Non-parametric data & discrete data"
author: B Kleinberg
subtitle: Dept of Security and Crime Science, UCL
output: html_notebook
---

## Aims of this notebook

- non-parametric data
    - correlation
    - mean comparison for two groups
    - mean comparison for two and more groups
- discrete data
    - 2-by-2 tables
    - R-by-C tables
    - Multidimensional arrays

    
## Requirements

We assume that you have:

- read the required literature for weeks 1-5
- revised the lectures
- completed the introductory R tutorials (12 steps & How to solve problems) as well as the tutorial from week 2
- completed the homework in this module so far
- replicated the code from the lectures (if concepts/R implementation is unclear)

If you struggle with basics of R, you may also find this online book useful: [https://bookdown.org/ndphillips/YaRrr/](https://bookdown.org/ndphillips/YaRrr/)

---

## Non-parametric data analysis

### Task 1: Correlation

### Task 2: Comparing two groups

### Task 3: Comparing 2 (or more) groups


## Discrete data

### Task 4: 2-by-2 tables

### Task 5: R-by-C tables

### Task 6: Multidimensional arrays



## END

---